### ISSUE TITLE
search URL is showing something like 127.0.0.1

### ISSUE THREAD

**Issue by Vishnu2jd** [vojkovic/searxng#10]
Search URL is showing https://127.0.0.1:7070/search?q=pihole&language=en-US&time_range=None&safesearch=1&categories=general  instead of normal URL. 
<img width="1393" alt="Screenshot 2022-06-12 at 3 46 09 PM" src="https://user-images.githubusercontent.com/87307728/173228553-458c2897-5d67-4668-b371-96fbaefe523e.png">

**Comment by vojkovic** [comment]
Thanks for your issue, I've fixed it in the nginx config.
