### ISSUE TITLE
Bug: alexandria engine

### ISSUE THREAD

**Issue by aqualandlover** [vojkovic/searxng#21]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/vojkovic/searxng
Branch: main
Version: 2022.08.01-7c9c1124

**How did you install SearXNG?**
using the official wiki 
**What happened?**
Errors: HTTP error unexpected crash

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

**Comment by vojkovic** [comment]
Unable to reproduce. Works on my instance currently.

**Comment by aqualandlover** [comment]
Hi,

Thank you, just checked it and the realibility increased from 6! To 70 percent.

Keep on going with the good work.

All the best,





Hand made and sent to you with 🌼



Please consider the environment before printing this email


________________________________

**Comment by allendema** [comment]
The API ans site were not responding yesterday.
