### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by aqualandlover** [vojkovic/searxng#24]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/vojkovic/searxng
Branch: main
Version: 2022.08.09-3d6b098a

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:107`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by vojkovic** [comment]
Looks like it's fixed now. Sometimes brave will rate limit the SearXNG instance as I do not use proxies to get results.

**Comment by aqualandlover** [comment]
Hi,

Thank you. Now that I am aware to the fact you are not using any proxies I'll wait a bit longer before notifying you...have a lovely day.

Sent from Re:Work<http://www.9folders.com/>

________________________________
